project:
  type: website
  output-dir: docs

website:
  title: "Blog de Juan Riera"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/juanriera/
      - icon: github
        href: https://github.com/juanriera/
      - icon: twitter
        href: https://twitter.com/@rieraprieto/
      - icon: mastodon
        href: https://mstdn.social/@juanriera/
    left:
      - text: "Sobre este blog"
        file: about_blog.qmd
format:
  html:
    theme: flatly
    css: styles.css
    
author-title: AUTOR
published-title: PUBLICADO
editor: visual

