project:
  type: website
  output-dir: docs

website:
  title: "Blog de Juan Riera"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/juanriera/
      - icon: github
        href: https://github.com/juanriera/
      - icon: bluesky
        href: https://bsky.app/profile/juanriera.bsky.social
      - icon: mastodon
        href: https://mstdn.social/@juanriera/
    left:
      - text: "Sobre este blog"
        file: about_blog.qmd
  comments:
    giscus:
      repo: juanriera/blog
      repo-id: R_kgDOI1wAcQ
      category: Announcements
      category-id: DIC_kwDOI1wAcc4C6dDb
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      theme: light
      language: es
      
format:
  html:
    theme: flatly
    css: styles.css
    
published-title: PUBLICADO
lang: es

